language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - '-.+'

script:
  - chmod +x ./gradlew build.gradle

deploy:
  provider: releases

  file: "/build/outputs/apk/release/2048-android-release.apk"
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    tags: true
